fix panic for Mpeg7 signature compare
livepeer/FFmpeg pull request #26
Opened 2022-01-25 14:31 UTC by oscar-davids

follow up to #[2175](https://github.com/livepeer/go-livepeer/issues/2175)

1.  review dangerous memory access code and [check ](https://github.com/livepeer/FFmpeg/blob/37b0e7e80582bd108cb2d2628592c86821505e98/libavfilter/vf_signature.c#L550)remain bits size while read buffer
2.  passed fuzzy [test](https://github.com/livepeer/lpms/pull/296) 
3.  plus - [free](https://github.com/livepeer/FFmpeg/blob/37b0e7e80582bd108cb2d2628592c86821505e98/libavfilter/vf_signature.c#L684) remain memory when import function return fail

2022-02-02 02:30 UTC, darkdarkdragon requested changes

2022-02-02 02:30 UTC, darkdarkdragon commented on libavfilter/vf_signature.c
> +        if(!scontexts[0].coarsesiglist) {
```suggestion
        if(scontexts[0].coarsesiglist) {
```
Probably intended to be that way?

2022-02-02 02:30 UTC, darkdarkdragon commented on libavfilter/vf_signature.c
> +		if(!scontexts[1].coarsesiglist) {
```suggestion
        if(scontexts[1].coarsesiglist) {
```

2022-02-07 14:17 UTC, yondonfu commented
Let's make sure to cleanup the [test](https://github.com/livepeer/lpms/pull/296) used to validate that this fixes the segfault and check that into LPMS as well so that we have the ability to continuously validate that there is no problematic segfault triggered by this code.

2022-02-07 15:33 UTC, darkdarkdragon approved these changes
LGTM

2022-02-08 00:51 UTC, merged